// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiVinculacionProyectosV2.Models;

#nullable disable

namespace WebApiVinculacionProyectosV2.Migrations
{
    [DbContext(typeof(ResidenciasDbContext))]
    [Migration("20260310032758_updateExpediente")]
    partial class updateExpediente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_spanish_ci")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Carreras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Carreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Contador Público"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Licenciatura en Administración"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Ingeniería Química"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Ingeniería Mecánica"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Ingeniería Industrial"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Ingeniería en Sistemas Computacionales"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Ingeniería en Gestión Empresarial"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Ingeniería Electrónica"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Ingeniería Eléctrica"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Ingeniería Civil"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Contacto", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Contactoemergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Parentesco")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Contactoemergencia", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContactoEmerg_EmailFormato", "email IS NULL OR email REGEXP '^[^[:space:]@]+@[^[:space:]@]+\\.[^[:space:]@]+$'");

                            t.HasCheckConstraint("CK_ContactoEmerg_TelFormato", "Telefono IS NULL OR Telefono REGEXP '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.DependenciaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DependenciaMedica", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "IMSS"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "ISSSTE"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "ISSFAM (Militar)"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "PEMEX"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Seguro privado"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Servicios de Salud del Estado"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Sin seguridad social"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Docentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idUsuario");

                    b.ToTable("Docentes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Docentes_RFC_Formato", "RFC IS NULL OR RFC REGEXP '^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$'");

                            t.HasCheckConstraint("CK_Docentes_Telefono10", "Telefono IS NULL OR Telefono REGEXP '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComentarioRevision")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("EstadoRevision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RevisadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("RutaFisica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("UrlExterna")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumento");

                    b.HasIndex("IdEstudiante", "TipoDocumento")
                        .IsUnique();

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CP")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext");

                    b.Property<int?>("Colonia")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Giro")
                        .HasColumnType("longtext");

                    b.Property<string>("Mision")
                        .HasColumnType("longtext");

                    b.Property<int?>("Municipio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PuestoTitular")
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Titular")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Empresas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Empresas_CP5", "CP IS NULL OR CP REGEXP '^[0-9]{5}$'");

                            t.HasCheckConstraint("CK_Empresas_RFC_Formato", "RFC REGEXP '^[A-ZÑ&]{3,4}[0-9]{6}[A-Z0-9]{3}$'");

                            t.HasCheckConstraint("CK_Empresas_Telefono10", "Telefono REGEXP '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Entregable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("IdEstadoEntregable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("IdEstudianteAutor")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEntregable")
                        .HasColumnType("int");

                    b.Property<int>("VersionActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoEntregable");

                    b.HasIndex("IdEstudianteAutor");

                    b.HasIndex("IdTipoEntregable");

                    b.HasIndex("IdProyecto", "IdTipoEntregable")
                        .IsUnique();

                    b.ToTable("Entregables", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.EntregableVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("IdEntregable")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudianteSubio")
                        .HasColumnType("int");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("RutaFisica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdEstudianteSubio");

                    b.HasIndex("IdEntregable", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("EntregableVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_EntregableVersion_NumeroVersion", "NumeroVersion >= 1");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Especializacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("Especializacion", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Activo = true,
                            descripcion = "Desarrollo de software"
                        },
                        new
                        {
                            id = 2,
                            Activo = true,
                            descripcion = "Redes y telecomunicaciones"
                        },
                        new
                        {
                            id = 3,
                            Activo = true,
                            descripcion = "Bases de datos"
                        },
                        new
                        {
                            id = 4,
                            Activo = true,
                            descripcion = "Gestión de proyectos"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Disponible"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "En Espera de Asignación de Revisor de Anteproyecto"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "En Espera de Revisión de Anteproyecto"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Anteproyecto Revisado"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "En Espera de Asignación de Asesor Interno"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "En Curso"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Finalizado"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.EstadoEntregable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("EstadoEntregable", null, t =>
                        {
                            t.HasCheckConstraint("CK_EstadoEntregable_Clave", "Clave IN ('PENDIENTE','EN_REVISION','CAMBIOS','APROBADO','RECHAZADO','CANCELADO')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "PENDIENTE",
                            Descripcion = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "EN_REVISION",
                            Descripcion = "En revisión"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Clave = "CAMBIOS",
                            Descripcion = "Con cambios"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Clave = "APROBADO",
                            Descripcion = "Aprobado"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Clave = "RECHAZADO",
                            Descripcion = "Rechazado"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Clave = "CANCELADO",
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Estudiantes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ciudad")
                        .HasColumnType("longtext");

                    b.Property<string>("correoPersonal")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cp")
                        .HasColumnType("longtext");

                    b.Property<string>("domicilio")
                        .HasColumnType("longtext");

                    b.Property<int?>("idContactoEmergencia")
                        .HasColumnType("int");

                    b.Property<int?>("idDependenciaMedica")
                        .HasColumnType("int");

                    b.Property<int?>("idProyecto")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("idcarrera")
                        .HasColumnType("int");

                    b.Property<string>("noControl")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("noSeguroSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("telefonoCelular")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.HasIndex("idContactoEmergencia");

                    b.HasIndex("idDependenciaMedica");

                    b.HasIndex("idProyecto");

                    b.HasIndex("idUsuario");

                    b.HasIndex("idcarrera");

                    b.ToTable("Estudiantes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Estudiantes_ApellidoMatSoloLetras", "ApellidoMaterno REGEXP '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+( [A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)*$'");

                            t.HasCheckConstraint("CK_Estudiantes_ApellidoPatSoloLetras", "ApellidoPaterno REGEXP '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+( [A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)*$'");

                            t.HasCheckConstraint("CK_Estudiantes_CorreoPersonalFormato", "correoPersonal IS NULL OR correoPersonal REGEXP '^[^[:space:]@]+@[^[:space:]@]+\\.[^[:space:]@]+$'");

                            t.HasCheckConstraint("CK_Estudiantes_NoControlFormato", "noControl IS NULL OR noControl REGEXP '^([0-9]{8}|[A-Za-z][0-9]{8})$'");

                            t.HasCheckConstraint("CK_Estudiantes_NombreSoloLetras", "Nombre REGEXP '^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+( [A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+)*$'");

                            t.HasCheckConstraint("CK_Estudiantes_TelCelFormato", "telefonoCelular IS NULL OR telefonoCelular REGEXP '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.InvitacionProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEstudianteCreador")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudianteInvitado")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEstudianteCreador");

                    b.HasIndex("IdEstudianteInvitado");

                    b.HasIndex("IdProyecto", "IdEstudianteInvitado")
                        .IsUnique();

                    b.ToTable("InvitacionProyecto", null, t =>
                        {
                            t.HasCheckConstraint("CK_InvitacionProyecto_Estado", "Estado IN ('PENDIENTE','ACEPTADA','RECHAZADA','CANCELADA')");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Modalidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Modalidad", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Activo = true,
                            Descripcion = "Presencial"
                        },
                        new
                        {
                            id = 2,
                            Activo = true,
                            Descripcion = "Mixta"
                        },
                        new
                        {
                            id = 3,
                            Activo = true,
                            Descripcion = "Virtual"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConsecutivoOficio")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("JefeDepartamentoNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrefijoOficio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.PeriodoMembrentado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PdfBytes")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoAcademicoId")
                        .IsUnique();

                    b.ToTable("PeriodosMembrentados");
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Permisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Permisos", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            Activo = true,
                            Descripcion = "Estudiante-Create"
                        },
                        new
                        {
                            id = 2,
                            Activo = true,
                            Descripcion = "Estudiante-Update"
                        },
                        new
                        {
                            id = 3,
                            Activo = true,
                            Descripcion = "Estudiante-Read"
                        },
                        new
                        {
                            id = 4,
                            Activo = true,
                            Descripcion = "Docente-Create"
                        },
                        new
                        {
                            id = 5,
                            Activo = true,
                            Descripcion = "Docente-Update"
                        },
                        new
                        {
                            id = 6,
                            Activo = true,
                            Descripcion = "Docente-Read"
                        },
                        new
                        {
                            id = 7,
                            Activo = true,
                            Descripcion = "Empresa-Create"
                        },
                        new
                        {
                            id = 8,
                            Activo = true,
                            Descripcion = "Empresa-Update"
                        },
                        new
                        {
                            id = 9,
                            Activo = true,
                            Descripcion = "Empresa-Read"
                        },
                        new
                        {
                            id = 10,
                            Activo = true,
                            Descripcion = "Proyecto-Create"
                        },
                        new
                        {
                            id = 11,
                            Activo = true,
                            Descripcion = "Proyecto-Update"
                        },
                        new
                        {
                            id = 12,
                            Activo = true,
                            Descripcion = "Proyecto-Read"
                        },
                        new
                        {
                            id = 13,
                            Activo = true,
                            Descripcion = "Usuario-Create"
                        },
                        new
                        {
                            id = 14,
                            Activo = true,
                            Descripcion = "Usuario-Update"
                        },
                        new
                        {
                            id = 15,
                            Activo = true,
                            Descripcion = "Usuario-Read"
                        },
                        new
                        {
                            id = 16,
                            Activo = true,
                            Descripcion = "Repositorio-Read"
                        },
                        new
                        {
                            id = 17,
                            Activo = true,
                            Descripcion = "Repositorio-Select"
                        },
                        new
                        {
                            id = 18,
                            Activo = true,
                            Descripcion = "Repositorio-Create"
                        },
                        new
                        {
                            id = 19,
                            Activo = true,
                            Descripcion = "Seguimiento-Read"
                        },
                        new
                        {
                            id = 20,
                            Activo = true,
                            Descripcion = "Seguimiento-Edit"
                        },
                        new
                        {
                            id = 21,
                            Activo = true,
                            Descripcion = "Perfil-Read"
                        },
                        new
                        {
                            id = 22,
                            Activo = true,
                            Descripcion = "Perfil-Edit"
                        },
                        new
                        {
                            id = 23,
                            Activo = true,
                            Descripcion = "PeriodoAcademico-Read"
                        },
                        new
                        {
                            id = 24,
                            Activo = true,
                            Descripcion = "DocenteProyecto-Edit"
                        },
                        new
                        {
                            id = 25,
                            Activo = true,
                            Descripcion = "DocenteProyecto-Read"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.ProyectoDocente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("FechaInscripcion")
                        .HasColumnType("date");

                    b.Property<int>("IdTipoRelacion")
                        .HasColumnType("int");

                    b.Property<int>("idDocente")
                        .HasColumnType("int");

                    b.Property<int>("idProyecto")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdTipoRelacion");

                    b.HasIndex("idDocente");

                    b.HasIndex("idProyecto")
                        .HasDatabaseName("IX_ProyectoDocente_idProyecto");

                    b.HasIndex("idProyecto", "IdTipoRelacion")
                        .HasDatabaseName("IX_ProyectoDocente_idProyecto_IdTipoRelacion");

                    b.HasIndex("idProyecto", "IdTipoRelacion", "idDocente")
                        .IsUnique()
                        .HasDatabaseName("IX_ProyectoDocente_idProyecto_IdTipoRelacion_idDocente");

                    b.ToTable("ProyectoDocente", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.ProyectoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreServidor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RutaFisica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProyecto")
                        .IsUnique();

                    b.ToTable("ProyectoDocumentos", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Proyectos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<TimeSpan?>("HorarioFinal")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HorarioInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstudianteCreador")
                        .HasColumnType("int");

                    b.Property<int?>("IdPeriodoAcademico")
                        .HasColumnType("int");

                    b.Property<int?>("NoResidentes")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .HasColumnType("longtext");

                    b.Property<bool>("PropuestaAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<int?>("idEspecializcion")
                        .HasColumnType("int");

                    b.Property<int?>("idEstado")
                        .HasColumnType("int");

                    b.Property<int?>("idModalidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstudianteCreador");

                    b.HasIndex("IdPeriodoAcademico");

                    b.HasIndex("idEspecializcion");

                    b.HasIndex("idEstado");

                    b.HasIndex("idModalidad");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.RevisionEntregable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<string>("Dictamen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasDefaultValue("CAMBIOS");

                    b.Property<DateTime>("FechaRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("IdDocenteRevisor")
                        .HasColumnType("int");

                    b.Property<int>("IdEntregableVersion")
                        .HasColumnType("int");

                    b.Property<string>("NombreOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreServidor")
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroRevision")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RutaFisica")
                        .HasColumnType("longtext");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdDocenteRevisor");

                    b.HasIndex("IdEntregableVersion", "NumeroRevision")
                        .IsUnique();

                    b.ToTable("RevisionEntregable", null, t =>
                        {
                            t.HasCheckConstraint("CK_RevisionEntregable_Dictamen", "Dictamen IN ('CAMBIOS','APROBADO','RECHAZADO')");

                            t.HasCheckConstraint("CK_RevisionEntregable_NumeroRevision", "NumeroRevision >= 1");
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Estudiante"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Docente"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Jefe de vinculación"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Jefe de Departamento"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.RolPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("idPermiso")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("idPermiso");

                    b.HasIndex("idRol");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            idPermiso = 1,
                            idRol = 1
                        },
                        new
                        {
                            Id = 2,
                            idPermiso = 2,
                            idRol = 1
                        },
                        new
                        {
                            Id = 3,
                            idPermiso = 3,
                            idRol = 1
                        },
                        new
                        {
                            Id = 4,
                            idPermiso = 4,
                            idRol = 1
                        },
                        new
                        {
                            Id = 5,
                            idPermiso = 5,
                            idRol = 1
                        },
                        new
                        {
                            Id = 6,
                            idPermiso = 6,
                            idRol = 1
                        },
                        new
                        {
                            Id = 14,
                            idPermiso = 7,
                            idRol = 1
                        },
                        new
                        {
                            Id = 15,
                            idPermiso = 8,
                            idRol = 1
                        },
                        new
                        {
                            Id = 16,
                            idPermiso = 9,
                            idRol = 1
                        },
                        new
                        {
                            Id = 17,
                            idPermiso = 10,
                            idRol = 1
                        },
                        new
                        {
                            Id = 18,
                            idPermiso = 11,
                            idRol = 1
                        },
                        new
                        {
                            Id = 19,
                            idPermiso = 12,
                            idRol = 1
                        },
                        new
                        {
                            Id = 20,
                            idPermiso = 13,
                            idRol = 1
                        },
                        new
                        {
                            Id = 21,
                            idPermiso = 14,
                            idRol = 1
                        },
                        new
                        {
                            Id = 22,
                            idPermiso = 15,
                            idRol = 1
                        },
                        new
                        {
                            Id = 23,
                            idPermiso = 16,
                            idRol = 1
                        },
                        new
                        {
                            Id = 24,
                            idPermiso = 17,
                            idRol = 1
                        },
                        new
                        {
                            Id = 25,
                            idPermiso = 18,
                            idRol = 1
                        },
                        new
                        {
                            Id = 26,
                            idPermiso = 19,
                            idRol = 1
                        },
                        new
                        {
                            Id = 27,
                            idPermiso = 20,
                            idRol = 1
                        },
                        new
                        {
                            Id = 28,
                            idPermiso = 21,
                            idRol = 1
                        },
                        new
                        {
                            Id = 29,
                            idPermiso = 22,
                            idRol = 1
                        },
                        new
                        {
                            Id = 30,
                            idPermiso = 23,
                            idRol = 1
                        },
                        new
                        {
                            Id = 31,
                            idPermiso = 24,
                            idRol = 1
                        },
                        new
                        {
                            Id = 7,
                            idPermiso = 16,
                            idRol = 2
                        },
                        new
                        {
                            Id = 8,
                            idPermiso = 17,
                            idRol = 2
                        },
                        new
                        {
                            Id = 9,
                            idPermiso = 18,
                            idRol = 2
                        },
                        new
                        {
                            Id = 10,
                            idPermiso = 19,
                            idRol = 2
                        },
                        new
                        {
                            Id = 11,
                            idPermiso = 20,
                            idRol = 2
                        },
                        new
                        {
                            Id = 12,
                            idPermiso = 21,
                            idRol = 2
                        },
                        new
                        {
                            Id = 13,
                            idPermiso = 22,
                            idRol = 2
                        },
                        new
                        {
                            Id = 32,
                            idPermiso = 24,
                            idRol = 3
                        },
                        new
                        {
                            Id = 55,
                            idPermiso = 25,
                            idRol = 3
                        },
                        new
                        {
                            Id = 56,
                            idPermiso = 21,
                            idRol = 3
                        },
                        new
                        {
                            Id = 57,
                            idPermiso = 22,
                            idRol = 3
                        },
                        new
                        {
                            Id = 33,
                            idPermiso = 1,
                            idRol = 4
                        },
                        new
                        {
                            Id = 34,
                            idPermiso = 2,
                            idRol = 4
                        },
                        new
                        {
                            Id = 35,
                            idPermiso = 3,
                            idRol = 4
                        },
                        new
                        {
                            Id = 36,
                            idPermiso = 4,
                            idRol = 4
                        },
                        new
                        {
                            Id = 37,
                            idPermiso = 5,
                            idRol = 4
                        },
                        new
                        {
                            Id = 38,
                            idPermiso = 6,
                            idRol = 4
                        },
                        new
                        {
                            Id = 39,
                            idPermiso = 7,
                            idRol = 4
                        },
                        new
                        {
                            Id = 40,
                            idPermiso = 8,
                            idRol = 4
                        },
                        new
                        {
                            Id = 41,
                            idPermiso = 9,
                            idRol = 4
                        },
                        new
                        {
                            Id = 42,
                            idPermiso = 10,
                            idRol = 4
                        },
                        new
                        {
                            Id = 43,
                            idPermiso = 11,
                            idRol = 4
                        },
                        new
                        {
                            Id = 44,
                            idPermiso = 12,
                            idRol = 4
                        },
                        new
                        {
                            Id = 45,
                            idPermiso = 13,
                            idRol = 4
                        },
                        new
                        {
                            Id = 46,
                            idPermiso = 14,
                            idRol = 4
                        },
                        new
                        {
                            Id = 47,
                            idPermiso = 15,
                            idRol = 4
                        },
                        new
                        {
                            Id = 48,
                            idPermiso = 19,
                            idRol = 4
                        },
                        new
                        {
                            Id = 49,
                            idPermiso = 20,
                            idRol = 4
                        },
                        new
                        {
                            Id = 50,
                            idPermiso = 21,
                            idRol = 4
                        },
                        new
                        {
                            Id = 51,
                            idPermiso = 22,
                            idRol = 4
                        },
                        new
                        {
                            Id = 52,
                            idPermiso = 23,
                            idRol = 4
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.SepomexColonia", b =>
                {
                    b.Property<string>("ColoniaId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Cr")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EstadoId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("FechaAct")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MunicipioId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ColoniaId");

                    b.HasIndex("Cp");

                    b.HasIndex("EstadoId", "MunicipioId");

                    b.ToTable("SepomexColonias", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.SepomexEstado", b =>
                {
                    b.Property<string>("EstadoId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Rango1")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rango2")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("EstadoId");

                    b.ToTable("SepomexEstados", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.SepomexMunicipio", b =>
                {
                    b.Property<string>("EstadoId")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MunicipioId")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Rango1")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rango2")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("EstadoId", "MunicipioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("SepomexMunicipios", (string)null);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Dictamen de autorización de comité académico (cuando sea necesario)"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Horario"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Cronograma 100%"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Solicitud de residencia sellada por la Div. Est. Prof."
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Carta de presentación"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Carta compromiso"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Carta de aceptación"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Descripcion = "Reporte parcial No. 1 sellado + hoja de revisores (asesor interno y REV1)"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Descripcion = "Reporte parcial No. 2 sellado + hoja de revisores (asesor interno y REV1)"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Descripcion = "Reporte final sellado + hoja de revisores (asesor interno, REV1, REV2 y REV3)"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Descripcion = "Carta de terminación sellada por Gest. Tec."
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Descripcion = "CD: informe final + SW instalable + manual técnico + manual de usuario (portada en etiqueta)"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Descripcion = "Acta de residencia profesional"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.TipoEntregable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("MaxRevisiones")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoEntregable", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Anteproyecto",
                            MaxRevisiones = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Evaluación Parcial 1"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Evaluación Parcial 2"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Evaluación Final"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.TipoRelacionDocenteProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("TipoRelacionDocenteProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "REVISOR_ANTEPROYECTO",
                            Descripcion = "Revisor de anteproyecto"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "ASESOR_INTERNO",
                            Descripcion = "Asesor interno"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Clave = "REVISOR_RESIDENCIA",
                            Descripcion = "Revisor de residencia"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdRol = 1,
                            IdUsuario = 1
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Correo_Formato", "Correo REGEXP '^[^[:space:]@]+@[^[:space:]@]+\\.[^[:space:]@]+$'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            ApellidoMaterno = "Trujillo",
                            ApellidoPaterno = "Alvarez",
                            Correo = "19161231@itoaxaca.edu.mx",
                            Nombre = "Luis Enrique",
                            PasswordHash = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92"
                        });
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Contacto", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Docentes", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Documento", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.TipoDocumento", null)
                        .WithMany()
                        .HasForeignKey("TipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Entregable", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.EstadoEntregable", null)
                        .WithMany()
                        .HasForeignKey("IdEstadoEntregable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudianteAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Proyectos", null)
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.TipoEntregable", null)
                        .WithMany()
                        .HasForeignKey("IdTipoEntregable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.EntregableVersion", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Entregable", null)
                        .WithMany()
                        .HasForeignKey("IdEntregable")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudianteSubio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Estudiantes", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Contactoemergencia", null)
                        .WithMany()
                        .HasForeignKey("idContactoEmergencia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.DependenciaMedica", null)
                        .WithMany()
                        .HasForeignKey("idDependenciaMedica")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Proyectos", null)
                        .WithMany()
                        .HasForeignKey("idProyecto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Carreras", null)
                        .WithMany()
                        .HasForeignKey("idcarrera")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.InvitacionProyecto", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudianteCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudianteInvitado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Proyectos", null)
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.PeriodoMembrentado", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.PeriodoAcademico", null)
                        .WithMany()
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.ProyectoDocente", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.TipoRelacionDocenteProyecto", null)
                        .WithMany()
                        .HasForeignKey("IdTipoRelacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Docentes", null)
                        .WithMany()
                        .HasForeignKey("idDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Proyectos", null)
                        .WithMany()
                        .HasForeignKey("idProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.ProyectoDocumento", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Proyectos", null)
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Proyectos", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Empresas", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estudiantes", null)
                        .WithMany()
                        .HasForeignKey("IdEstudianteCreador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.PeriodoAcademico", null)
                        .WithMany()
                        .HasForeignKey("IdPeriodoAcademico")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Especializacion", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("idEspecializcion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Estado", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("idEstado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Modalidad", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("idModalidad")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.RevisionEntregable", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Docentes", null)
                        .WithMany()
                        .HasForeignKey("IdDocenteRevisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.EntregableVersion", null)
                        .WithMany()
                        .HasForeignKey("IdEntregableVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.RolPermiso", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Permisos", null)
                        .WithMany()
                        .HasForeignKey("idPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.UsuarioRol", b =>
                {
                    b.HasOne("WebApiVinculacionProyectosV2.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiVinculacionProyectosV2.Models.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Empresas", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Especializacion", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Estado", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("WebApiVinculacionProyectosV2.Models.Modalidad", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
